### PR TITLE
fix wrong call to get modifiers as array

### PR DESCRIPTION
**Pull request by tehron**

### CODE REVIEW

**Comment by gizmore** [comment]
Wouldn't that skip modifiersA() from certain powerful runes?
array_merge maybe?

**Comment by tehron** [comment]
I don't understand. Aren't all runes instance of SR_Rune? `getItemModifiersA($player)` returns `array()` always then?

**Comment by gizmore** [comment]
There are also LO_Rune.... up to MON_Rune which additionally adds essence just by being a MON_Rune.

LO, UM, ON, EE, PA, MON is the sequence of powers :)

**Comment by tehron** [comment]
Anyways, it should be pretty ... whatever. I think `getItemModifiersB()` is correct and sufficient, because you want to know, if the rune has any modifiers which can be applied to equipment on upgrade.

**Comment by gizmore** [comment]
I think one quest has 3 blank MON_Runes as reward :/

**Review by gizmore — COMMENTED** [review]
looks good

**Pull request merged**
